### PR TITLE
Update mysql plugin to 1.8 so that we can track user_stats

### PR DESCRIPTION
**Pull request by yabberyabber**
Tested by deploying on bs205 as well as mysql1 and mysql2 masters

### CODE REVIEW

**Review by kthommandra — COMMENTED** [review]
Can we change the plugin to not use TLS and thus avoid merging in the "internal/tls" ?
That way we are not mixing a more recent non-plugin "internal/tls" with rest of the Telegraf code.

**Comment by yabberyabber** [comment]
Done - using old auth method (and diff got much shorter 😇 )

**Review by kthommandra — APPROVED** [review]
awesome! Thanks.

**Comment by kthommandra** [comment]
@Manoj321 can you also take a quick look

**Comment by manojm321** [comment]
@yabberyabber 

> Tested by deploying on bs205 as well as mysql1 and mysql2 masters

I assume you were able to build the rpm successfully? Apart from mysql stats were you able to see general server metrics as well?

**Comment by yabberyabber** [comment]
I checked out the hosts on the server-metrics dashboard and everything that's there that was publishing before is still publishing now

**Pull request merged**
