### PR TITLE
TELEGRAF CONFIG CHANGES

### PR DESCRIPTION
**Pull request by StephenSDaily**
"namepass" will only work with measurement names. Not the name of plugin.

### CODE REVIEW

**Comment by kthommandra** [comment]
just add a note about the testing done or not needed for each config

**Comment by StephenSDaily** [comment]
Tested the configurations by moving them to the appropriate server and making sure they were generating the correct data. Did not try to build.

**Comment by kthommandra** [comment]
When configs are changed, the corresponding ITER in arista-package.sh should be incremented

**Comment by kthommandra** [comment]
I noticed that in commit
https://github.com/aristanetworks/telegraf/commit/663367f4fb6953232140343dda36d9c90838a778

There was no change to config RPM VER in arista-package.sh since the Config RPMs started using new format in that change my recommendation would be to bump up the VER for all Config RPMs even those not changed in this particular commit
The binary RPM ITER should also be incremented

Once the config RPMs are build it would be best to test out the binary and config RPM by upgrading a user server. You can copy the RPMs from your local workspace to /tmp on a user server and try out "sudo yum localinstall telegraf-Linux" and confirm that both telegraf and telegraf-Linux get updated and stats for that user server look fine after the upgrade.

**Pull request closed without merging**
